const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best'),lengthEl=document.querySelector('#length'),statusEl=document.querySelector('#statusText'),startCard=document.querySelector('#startCard'),startButton=document.querySelector('#startButton'),pauseButton=document.querySelector('#pauseButton'),restartButton=document.querySelector('#restartButton'),scoresEl=document.querySelector('#scores'),emptyScores=document.querySelector('#emptyScores');
const SIZE=24,SCORE_KEY='anybot.orbit-snake.high-scores.v1',dirs={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}},opposite={up:'down',down:'up',left:'right',right:'left'};
let snake,food,direction,queuedDirection,score,running,paused,tickMs,lastTick,raf,particles,stars,touchStart;
function loadScores(){try{return JSON.parse(localStorage.getItem(SCORE_KEY)||'[]').filter(s=>s&&Number.isFinite(s.score)).slice(0,5)}catch{return[]}}
function saveScore(){if(score<1)return;const scores=[...loadScores(),{score,length:snake.length,date:new Date().toISOString()}].sort((a,b)=>b.score-a.score).slice(0,5);localStorage.setItem(SCORE_KEY,JSON.stringify(scores));renderScores()}
function renderScores(){const scores=loadScores();scoresEl.innerHTML='';emptyScores.hidden=scores.length>0;scores.forEach(s=>{const li=document.createElement('li'),date=new Date(s.date);li.innerHTML=`<span>${date.toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><strong>${s.score}</strong><small>${s.length} cells</small>`;scoresEl.append(li)});bestEl.textContent=scores[0]?.score||0}
function reset(){snake=[{x:11,y:12},{x:10,y:12},{x:9,y:12},{x:8,y:12}];direction='right';queuedDirection='right';score=0;tickMs=145;running=false;paused=false;particles=[];food=placeFood();updateHud();statusEl.textContent='READY TO LAUNCH';pauseButton.disabled=true;pauseButton.textContent='Pause';startCard.classList.remove('hidden')}
function placeFood(){let cell;do{cell={x:Math.floor(Math.random()*SIZE),y:Math.floor(Math.random()*SIZE)}}while(snake?.some(s=>s.x===cell.x&&s.y===cell.y));return cell}
function updateHud(){scoreEl.textContent=score;lengthEl.textContent=snake.length}
function start(){running=true;paused=false;lastTick=performance.now();startCard.classList.add('hidden');pauseButton.disabled=false;statusEl.textContent='SIGNAL ACTIVE';canvas.focus();cancelAnimationFrame(raf);raf=requestAnimationFrame(frame)}
function end(){running=false;paused=false;saveScore();pauseButton.disabled=true;statusEl.textContent='ORBIT LOST';startCard.classList.remove('hidden');startButton.textContent='Launch another run ↗';startCard.querySelector('h2').innerHTML='Signal lost.<br /><em>Try again?</em>';startCard.querySelector('p:not(.kicker)').textContent=`You scored ${score} points and reached ${snake.length} cells.`;draw(performance.now())}
function setDirection(next){if(!dirs[next]||opposite[direction]===next)return;queuedDirection=next;if(!running)start()}
function step(){direction=queuedDirection;const head={x:snake[0].x+dirs[direction].x,y:snake[0].y+dirs[direction].y};if(head.x<0||head.y<0||head.x>=SIZE||head.y>=SIZE||snake.some((s,i)=>i>0&&s.x===head.x&&s.y===head.y)){end();return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score+=10;tickMs=Math.max(72,tickMs-5);for(let i=0;i<14;i++)particles.push({x:(food.x+.5)/SIZE,y:(food.y+.5)/SIZE,vx:(Math.random()-.5)*.012,vy:(Math.random()-.5)*.012,life:1});food=placeFood();updateHud()}else snake.pop();updateHud()}
function frame(now){if(running){if(!paused&&now-lastTick>=tickMs){lastTick=now;step()}draw(now);raf=requestAnimationFrame(frame)}}
function roundedCell(x,y,size){if(typeof ctx.roundRect==='function'){ctx.roundRect(x,y,size,size,9);return}ctx.rect(x,y,size,size)}
function draw(now=performance.now()){const w=canvas.width,h=canvas.height,c=w/SIZE;ctx.clearRect(0,0,w,h);const g=ctx.createRadialGradient(w*.5,h*.45,10,w*.5,h*.5,w*.72);g.addColorStop(0,'#171943');g.addColorStop(1,'#070a18');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);if(!stars)stars=Array.from({length:70},()=>({x:Math.random(),y:Math.random(),r:Math.random()*1.6,a:.2+Math.random()*.6}));stars.forEach(s=>{ctx.fillStyle=`rgba(179,190,255,${s.a*(.65+.35*Math.sin(now/900+s.x*9))})`;ctx.fillRect(s.x*w,s.y*h,s.r,s.r)});ctx.strokeStyle='rgba(126,139,220,.1)';ctx.lineWidth=1;for(let i=1;i<SIZE;i++){ctx.beginPath();ctx.moveTo(i*c,0);ctx.lineTo(i*c,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*c);ctx.lineTo(w,i*c);ctx.stroke()}if(food){const fx=(food.x+.5)*c,fy=(food.y+.5)*c,pulse=1+Math.sin(now/180)*.12;ctx.shadowBlur=30;ctx.shadowColor='#57efc2';ctx.fillStyle='#57efc2';ctx.beginPath();ctx.arc(fx,fy,9*pulse,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#eafff8';ctx.beginPath();ctx.arc(fx-2,fy-2,3,0,Math.PI*2);ctx.fill()}snake.forEach((s,i)=>{const x=s.x*c+3,y=s.y*c+3,size=c-6;ctx.shadowBlur=i===0?28:13;ctx.shadowColor=i===0?'#b8a5ff':'#8e75f5';const grad=ctx.createLinearGradient(x,y,x+size,y+size);grad.addColorStop(0,i===0?'#d7ceff':'#a58eff');grad.addColorStop(1,i===0?'#735de4':'#5847b6');ctx.fillStyle=grad;ctx.beginPath();roundedCell(x,y,size);ctx.fill();ctx.shadowBlur=0;if(i===0){ctx.fillStyle='#090b1b';ctx.beginPath();ctx.arc(x+size*.34,y+size*.36,2.3,0,Math.PI*2);ctx.arc(x+size*.66,y+size*.36,2.3,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#090b1b';ctx.lineWidth=1.8;ctx.beginPath();ctx.arc(x+size*.5,y+size*.5,6,0.15,Math.PI-.15);ctx.stroke()}});particles=particles.filter(p=>p.life>0);particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.life=Math.max(0,p.life-.025);if(p.life<=0)return;ctx.fillStyle=`rgba(87,239,194,${p.life})`;ctx.beginPath();ctx.arc(p.x*w,p.y*h,3*p.life,0,Math.PI*2);ctx.fill()});if(paused){ctx.fillStyle='rgba(7,10,22,.62)';ctx.fillRect(0,0,w,h);ctx.fillStyle='#f2f3ff';ctx.font='600 32px Space Grotesk';ctx.textAlign='center';ctx.fillText('PAUSED',w/2,h/2)}}
function togglePause(){if(!running)return;paused=!paused;pauseButton.textContent=paused?'Resume':'Pause';statusEl.textContent=paused?'SIGNAL PAUSED':'SIGNAL ACTIVE';if(!paused)lastTick=performance.now()}
document.addEventListener('keydown',e=>{const map={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};if(map[e.key]){e.preventDefault();setDirection(map[e.key])}else if(e.key===' '){e.preventDefault();togglePause()}else if(e.key==='Escape'){reset();draw()}});
document.querySelectorAll('[data-dir]').forEach(b=>b.addEventListener('click',()=>setDirection(b.dataset.dir)));startButton.addEventListener('click',start);pauseButton.addEventListener('click',togglePause);restartButton.addEventListener('click',()=>{reset();draw()});canvas.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStart={x:t.clientX,y:t.clientY}},{passive:true});canvas.addEventListener('touchend',e=>{if(!touchStart)return;const t=e.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;touchStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<20)return;setDirection(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'))},{passive:true});
renderScores();reset();draw();

// Deterministic seam used by the browser acceptance tests. It is only exposed
// when ?test=1 is present, so normal players never see or depend on it.
if(new URLSearchParams(location.search).has('test')){
  window.__orbitSnakeTest={
    getState:()=>({snake:snake.map(s=>({...s})),food:{...food},direction,score,length:snake.length,running,paused}),
    setFood:(x,y)=>{food={x:Number(x),y:Number(y)};draw()},
    setDirection:(next)=>setDirection(next),
    tick:()=>{if(!running)start();step();draw()}
  };
}
